// Auto-generated by auto_probe_pcb.py -- Altium PCB-library DelphiScript.
// Open a PCB library FIRST: File > New > Library > PCB Library, make that
// .PcbLib the ACTIVE document, then File > Run Script... and run
// GenerateFootprint. Builds one footprint per net class; each holds that
// class's probe-card lands (pad designators = land ids) at their real board
// positions relative to the die centre. Place them all at the same origin to
// reconstruct the complete land pattern.

Var
    Lib : IPCB_Library;
    FP  : IPCB_LibComponent;

Procedure AddFPPad(XMM, YMM : Double; Desig : String);
Var Pad;
Begin
    Pad := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    Pad.X := MMsToCoord(XMM);
    Pad.Y := MMsToCoord(YMM);
    Pad.Layer := eMultiLayer;
    Pad.TopShape := eRounded;
    Pad.MidShape := eRounded;
    Pad.BotShape := eRounded;
    Pad.TopXSize := MMsToCoord(1.0000); Pad.TopYSize := MMsToCoord(1.0000);
    Pad.MidXSize := MMsToCoord(1.0000); Pad.MidYSize := MMsToCoord(1.0000);
    Pad.BotXSize := MMsToCoord(1.0000); Pad.BotYSize := MMsToCoord(1.0000);
    Pad.HoleSize := MMsToCoord(0.5080);
    Pad.Plated := True;
    Pad.Name := Desig;
    FP.AddPCBObject(Pad);
End;

// --- start a named footprint. Drops any footprint of the same name from a
// --- previous run first, so re-running replaces instead of colliding.
// --- CreateNewComponent is the library-level call used by working scripts;
// --- it is equivalent to PCBServer.CreatePCBLibComp.
Procedure StartFP(Nm : String);
Var Old;
Begin
    Old := Lib.GetComponentByName(Nm);
    If Old <> Nil Then
    Begin
        Lib.RemoveComponent(Old);
        Lib.DeRegisterComponent(Old);
    End;
    FP := Lib.CreateNewComponent;
    FP.Name := Nm;
End;

Procedure EndFP;
Begin
    Lib.RegisterComponent(FP);
    // must SetState_CurrentComponent (not a plain property assign) or the
    // footprint origin / bounding box come out wrong.
    Lib.SetState_CurrentComponent(FP);
End;


// Power -- 177 lands
Procedure BuildFP0;
Begin
    StartFP('ProbeCard_Power');
    AddFPPad(-9.4768, 22.9929, 'T25');
    AddFPPad(-7.3708, 24.1929, 'T28');
    AddFPPad(17.1992, 22.9929, 'T63');
    AddFPPad(-7.0324, -24.1929, 'B24');
    AddFPPad(-4.9264, -22.9929, 'B27');
    AddFPPad(-26.8250, 7.6257, 'L31');
    AddFPPad(28.0250, 7.4711, 'R34');
    AddFPPad(5.6036, -24.1929, 'B42');
    AddFPPad(6.3056, -22.9929, 'B43');
    AddFPPad(-18.2644, -24.1929, 'B8');
    AddFPPad(-17.5624, -22.9929, 'B9');
    AddFPPad(-25.6228, 24.1929, 'T2');
    AddFPPad(-20.7088, 22.9929, 'T9');
    AddFPPad(-8.7748, 24.1929, 'T26');
    AddFPPad(-2.4568, 22.9929, 'T35');
    AddFPPad(3.8612, 24.1929, 'T44');
    AddFPPad(10.1792, 22.9929, 'T53');
    AddFPPad(16.4972, 24.1929, 'T62');
    AddFPPad(25.6232, 22.9929, 'T75');
    AddFPPad(-6.3304, -22.9929, 'B25');
    AddFPPad(-26.8250, -6.4143, 'L11');
    AddFPPad(-28.0250, -1.5003, 'L18');
    AddFPPad(-26.8250, -0.7983, 'L19');
    AddFPPad(-26.8250, 2.0097, 'L23');
    AddFPPad(-28.0250, 2.7117, 'L24');
    AddFPPad(-26.8250, 3.4137, 'L25');
    AddFPPad(26.8250, 5.3651, 'R31');
    AddFPPad(-1.0528, 22.9929, 'T37');
    AddFPPad(2.4572, 24.1929, 'T42');
    AddFPPad(1.3916, -24.1929, 'B36');
    AddFPPad(4.9016, -22.9929, 'B41');
    AddFPPad(-13.3504, -22.9929, 'B15');
    AddFPPad(-16.8604, -24.1929, 'B10');
    AddFPPad(-17.9008, 22.9929, 'T13');
    AddFPPad(-19.3048, 22.9929, 'T11');
    AddFPPad(26.8250, -10.0789, 'R9');
    AddFPPad(26.8250, -5.8669, 'R15');
    AddFPPad(28.0250, -3.7609, 'R18');
    AddFPPad(28.0250, 0.4511, 'R24');
    AddFPPad(-21.4108, 24.1929, 'T8');
    AddFPPad(-15.0928, 22.9929, 'T17');
    AddFPPad(-12.9868, 24.1929, 'T20');
    AddFPPad(-8.0728, 22.9929, 'T27');
    AddFPPad(-3.8608, 22.9929, 'T33');
    AddFPPad(-1.7548, 24.1929, 'T36');
    AddFPPad(-12.6484, -24.1929, 'B16');
    AddFPPad(-10.5424, -22.9929, 'B19');
    AddFPPad(-5.6284, -24.1929, 'B26');
    AddFPPad(-1.4164, -24.1929, 'B32');
    AddFPPad(0.6896, -22.9929, 'B35');
    AddFPPad(-28.0250, 8.3277, 'L32');
    AddFPPad(-26.8250, 9.0297, 'L33');
    AddFPPad(-28.0250, 9.7317, 'L34');
    AddFPPad(-10.8808, 22.9929, 'T23');
    AddFPPad(-5.9668, 24.1929, 'T30');
    AddFPPad(-8.4364, -24.1929, 'B22');
    AddFPPad(-3.5224, -22.9929, 'B29');
    AddFPPad(4.5632, 22.9929, 'T45');
    AddFPPad(8.7752, 22.9929, 'T51');
    AddFPPad(12.9872, 22.9929, 'T57');
    AddFPPad(7.0076, -24.1929, 'B44');
    AddFPPad(11.2196, -24.1929, 'B50');
    AddFPPad(11.9216, -22.9929, 'B51');
    AddFPPad(15.4316, -24.1929, 'B56');
    AddFPPad(16.1336, -22.9929, 'B57');
    AddFPPad(28.0250, -9.3769, 'R10');
    AddFPPad(28.0250, -5.1649, 'R16');
    AddFPPad(26.8250, -3.0589, 'R19');
    AddFPPad(26.8250, 1.1531, 'R25');
    AddFPPad(-28.0250, 6.9237, 'L30');
    AddFPPad(-26.8250, 0.6057, 'L21');
    AddFPPad(26.8250, 10.9811, 'R39');
    AddFPPad(-19.6684, -24.1929, 'B6');
    AddFPPad(17.9012, 24.1929, 'T64');
    AddFPPad(12.6236, -24.1929, 'B52');
    AddFPPad(26.8250, -12.8869, 'R5');
    AddFPPad(26.8250, 3.9611, 'R29');
    AddFPPad(-0.3508, 24.1929, 'T38');
    AddFPPad(1.7552, 22.9929, 'T41');
    AddFPPad(2.0936, -22.9929, 'B37');
    AddFPPad(4.1996, -24.1929, 'B40');
    AddFPPad(-14.0524, -24.1929, 'B14');
    AddFPPad(-16.1584, -22.9929, 'B11');
    AddFPPad(-16.4968, 22.9929, 'T15');
    AddFPPad(-18.6028, 24.1929, 'T12');
    AddFPPad(-0.7144, -22.9929, 'B33');
    AddFPPad(-11.2444, -24.1929, 'B18');
    AddFPPad(6.6692, 24.1929, 'T48');
    AddFPPad(10.8812, 24.1929, 'T54');
    AddFPPad(15.0932, 24.1929, 'T60');
    AddFPPad(9.1136, -22.9929, 'B47');
    AddFPPad(13.3256, -22.9929, 'B53');
    AddFPPad(17.5376, -22.9929, 'B59');
    AddFPPad(18.2396, -24.1929, 'B60');
    AddFPPad(18.9416, -22.9929, 'B61');
    AddFPPad(28.0250, -12.1849, 'R6');
    AddFPPad(26.8250, -11.4829, 'R7');
    AddFPPad(26.8250, -7.2709, 'R13');
    AddFPPad(28.0250, -0.9529, 'R22');
    AddFPPad(28.0250, 3.2591, 'R28');
    AddFPPad(-13.6888, 22.9929, 'T19');
    AddFPPad(-26.8250, 13.2417, 'L39');
    AddFPPad(26.8250, 15.1931, 'R45');
    AddFPPad(-26.3248, 22.9929, 'T1');
    AddFPPad(-24.9208, 22.9929, 'T3');
    AddFPPad(-23.5168, 22.9929, 'T5');
    AddFPPad(-22.8148, 24.1929, 'T6');
    AddFPPad(-17.1988, 24.1929, 'T14');
    AddFPPad(-14.3908, 24.1929, 'T18');
    AddFPPad(-12.2848, 22.9929, 'T21');
    AddFPPad(-4.5628, 24.1929, 'T32');
    AddFPPad(0.3512, 22.9929, 'T39');
    AddFPPad(22.8152, 22.9929, 'T71');
    AddFPPad(23.5172, 24.1929, 'T72');
    AddFPPad(24.9212, 24.1929, 'T74');
    AddFPPad(26.3252, 24.1929, 'T76');
    AddFPPad(-23.1784, -22.9929, 'B1');
    AddFPPad(-21.7744, -22.9929, 'B3');
    AddFPPad(-15.4564, -24.1929, 'B12');
    AddFPPad(-14.7544, -22.9929, 'B13');
    AddFPPad(-11.9464, -22.9929, 'B17');
    AddFPPad(-9.8404, -24.1929, 'B20');
    AddFPPad(-2.1184, -22.9929, 'B31');
    AddFPPad(-0.0124, -24.1929, 'B34');
    AddFPPad(2.7956, -24.1929, 'B38');
    AddFPPad(-26.8250, -13.4343, 'L1');
    AddFPPad(-28.0250, -9.9243, 'L6');
    AddFPPad(-28.0250, -8.5203, 'L8');
    AddFPPad(-26.8250, -7.8183, 'L9');
    AddFPPad(-28.0250, -7.1163, 'L10');
    AddFPPad(-28.0250, -5.7123, 'L12');
    AddFPPad(-26.8250, -5.0103, 'L13');
    AddFPPad(-28.0250, -4.3083, 'L14');
    AddFPPad(-26.8250, -2.2023, 'L17');
    AddFPPad(-28.0250, 4.1157, 'L26');
    AddFPPad(-26.8250, 4.8177, 'L27');
    AddFPPad(-28.0250, 12.5397, 'L38');
    AddFPPad(-28.0250, 13.9437, 'L40');
    AddFPPad(28.0250, 6.0671, 'R32');
    AddFPPad(28.0250, 10.2791, 'R38');
    AddFPPad(26.8250, 12.3851, 'R41');
    AddFPPad(26.8250, 13.7891, 'R43');
    AddFPPad(28.0250, 14.4911, 'R44');
    AddFPPad(28.0250, 15.8951, 'R46');
    AddFPPad(5.9672, 22.9929, 'T47');
    AddFPPad(8.0732, 24.1929, 'T50');
    AddFPPad(12.2852, 24.1929, 'T56');
    AddFPPad(14.3912, 22.9929, 'T59');
    AddFPPad(8.4116, -24.1929, 'B46');
    AddFPPad(9.8156, -24.1929, 'B48');
    AddFPPad(10.5176, -22.9929, 'B49');
    AddFPPad(14.0276, -24.1929, 'B54');
    AddFPPad(14.7296, -22.9929, 'B55');
    AddFPPad(16.8356, -24.1929, 'B58');
    AddFPPad(19.6436, -24.1929, 'B62');
    AddFPPad(20.3456, -22.9929, 'B63');
    AddFPPad(21.0476, -24.1929, 'B64');
    AddFPPad(21.7496, -22.9929, 'B65');
    AddFPPad(22.4516, -24.1929, 'B66');
    AddFPPad(26.8250, -15.6949, 'R1');
    AddFPPad(28.0250, -14.9929, 'R2');
    AddFPPad(26.8250, -14.2909, 'R3');
    AddFPPad(28.0250, -13.5889, 'R4');
    AddFPPad(28.0250, -10.7809, 'R8');
    AddFPPad(26.8250, -8.6749, 'R11');
    AddFPPad(28.0250, -7.9729, 'R12');
    AddFPPad(28.0250, -6.5689, 'R14');
    AddFPPad(26.8250, -4.4629, 'R17');
    AddFPPad(28.0250, -2.3569, 'R20');
    AddFPPad(26.8250, -0.2509, 'R23');
    AddFPPad(28.0250, 1.8551, 'R26');
    AddFPPad(-28.0250, 11.1357, 'L36');
    AddFPPad(28.0250, 13.0871, 'R42');
    AddFPPad(-10.1788, 24.1929, 'T24');
    AddFPPad(-6.6688, 22.9929, 'T29');
    AddFPPad(-7.7344, -22.9929, 'B23');
    AddFPPad(-4.2244, -24.1929, 'B28');
    EndFP;
End;

// Digital -- 22 lands
Procedure BuildFP1;
Begin
    StartFP('ProbeCard_Digital');
    AddFPPad(-26.8250, -9.2223, 'L7');
    AddFPPad(-26.8250, -10.6263, 'L5');
    AddFPPad(-26.8250, -12.0303, 'L3');
    AddFPPad(-3.1588, 24.1929, 'T34');
    AddFPPad(13.6892, 24.1929, 'T58');
    AddFPPad(15.7952, 22.9929, 'T61');
    AddFPPad(24.2192, 22.9929, 'T73');
    AddFPPad(22.1132, 24.1929, 'T70');
    AddFPPad(20.0072, 22.9929, 'T67');
    AddFPPad(-15.7948, 24.1929, 'T16');
    AddFPPad(-11.5828, 24.1929, 'T22');
    AddFPPad(11.5832, 22.9929, 'T55');
    AddFPPad(9.4772, 24.1929, 'T52');
    AddFPPad(1.0532, 24.1929, 'T40');
    AddFPPad(5.2652, 24.1929, 'T46');
    AddFPPad(3.1592, 22.9929, 'T43');
    AddFPPad(-20.0068, 24.1929, 'T10');
    AddFPPad(-22.1128, 22.9929, 'T7');
    AddFPPad(-5.2648, 22.9929, 'T31');
    AddFPPad(-24.2188, 24.1929, 'T4');
    AddFPPad(-28.0250, -11.3283, 'L4');
    AddFPPad(-28.0250, -12.7323, 'L2');
    EndFP;
End;

// Analog -- 19 lands
Procedure BuildFP2;
Begin
    StartFP('ProbeCard_Analog');
    AddFPPad(28.0250, 11.6831, 'R40');
    AddFPPad(26.8250, 6.7691, 'R33');
    AddFPPad(28.0250, 8.8751, 'R36');
    AddFPPad(18.6032, 22.9929, 'T65');
    AddFPPad(20.7092, 24.1929, 'T68');
    AddFPPad(-20.3704, -22.9929, 'B5');
    AddFPPad(-18.9664, -22.9929, 'B7');
    AddFPPad(-28.0250, 5.5197, 'L28');
    AddFPPad(21.4112, 22.9929, 'T69');
    AddFPPad(19.3052, 24.1929, 'T66');
    AddFPPad(-28.0250, 1.3077, 'L22');
    AddFPPad(-28.0250, -0.0963, 'L20');
    AddFPPad(-26.8250, 6.2217, 'L29');
    AddFPPad(26.8250, 2.5571, 'R27');
    AddFPPad(-9.1384, -22.9929, 'B21');
    AddFPPad(-2.8204, -24.1929, 'B30');
    AddFPPad(7.3712, 22.9929, 'T49');
    AddFPPad(26.8250, -1.6549, 'R21');
    AddFPPad(28.0250, 4.6631, 'R30');
    EndFP;
End;

// RF-DIFFERENTIAL PAIR 100 OHM -- 6 lands
Procedure BuildFP3;
Begin
    StartFP('ProbeCard_RF_DIFFERENTIAL_PAIR_100_OHM');
    AddFPPad(7.7096, -22.9929, 'B45');
    AddFPPad(3.4976, -22.9929, 'B39');
    AddFPPad(-26.8250, 10.4337, 'L35');
    AddFPPad(-26.8250, 11.8377, 'L37');
    AddFPPad(-22.4764, -24.1929, 'B2');
    AddFPPad(-21.0724, -24.1929, 'B4');
    EndFP;
End;

// RF-SINGLE ENDED 50 OHM -- 4 lands
Procedure BuildFP4;
Begin
    StartFP('ProbeCard_RF_SINGLE_ENDED_50_OHM');
    AddFPPad(-28.0250, -2.9043, 'L16');
    AddFPPad(26.8250, 8.1731, 'R35');
    AddFPPad(-26.8250, -3.6063, 'L15');
    AddFPPad(26.8250, 9.5771, 'R37');
    EndFP;
End;

Procedure GenerateFootprint;
Begin
    If PCBServer = Nil Then
    Begin
        ShowMessage('PCBServer is nil -- the PCB editor is not loaded.');
        Exit;
    End;
    Lib := PCBServer.GetCurrentPCBLibrary;
    If Lib = Nil Then
    Begin
        ShowMessage('No PCB library open. Open the .PcbLib, click its tab so it ' +
            'is the ACTIVE document, then run this again.');
        Exit;
    End;

    PCBServer.PreProcess;
    BuildFP0;
    BuildFP1;
    BuildFP2;
    BuildFP3;
    BuildFP4;
    PCBServer.PostProcess;

    Lib.Board.ViewManager_FullUpdate;
    ShowMessage('Built 5 probe-card footprints ' +
        '(228 pads total). Save the .PcbLib.');
End;