// Auto-generated by auto_probe_pcb.py -- Altium Sch-library DelphiScript.
// Open a schematic library FIRST: File > New > Library > Schematic Library,
// make that .SchLib the ACTIVE document, then File > Run Script... and run
// GenerateSymbol. Builds one single-part component per net class, each
// carrying a footprint-model reference to the PcbLib footprint of the same
// name. Place all of them to cover the whole probe card.

Var
    Lib  : ISch_Lib;
    Comp : ISch_Component;

Procedure AddRect(Xmil, Ymil, Wmil, Hmil : Integer);
Var R;
Begin
    R := SchServer.SchObjectFactory(eRectangle, eCreate_GlobalCopy);
    R.OwnerPartId := 1;
    R.OwnerPartDisplayMode := 0;
    R.Location := Point(MilsToCoord(Xmil), MilsToCoord(Ymil - Hmil));
    R.Corner := Point(MilsToCoord(Xmil + Wmil), MilsToCoord(Ymil));
    R.LineWidth := eSmall;
    R.IsSolid := True;
    R.AreaColor := $00E7FFFF;
    R.Color := $00000080;
    Comp.AddSchObject(R);
End;

Procedure AddPin(Xmil, Ymil : Integer; Desig, Nm : String);
Var Pin;
Begin
    Pin := SchServer.SchObjectFactory(ePin, eCreate_GlobalCopy);
    Pin.OwnerPartId := 1;
    Pin.OwnerPartDisplayMode := 0;
    Pin.Orientation := eRotate0;
    Pin.Location := Point(MilsToCoord(Xmil - 300), MilsToCoord(Ymil));
    Pin.PinLength := MilsToCoord(300);
    Pin.Designator := Desig;
    Pin.Name := Nm;
    Pin.ShowName := True;
    Pin.ShowDesignator := True;
    Pin.Electrical := eElectricPassive;
    Comp.AddSchObject(Pin);
End;

Procedure StartComp(LibRef, Descr : String);
Begin
    Comp := SchServer.SchObjectFactory(eSchComponent, eCreate_GlobalCopy);
    Comp.LibReference := LibRef;
    Comp.ComponentDescription := Descr;
    Comp.Designator.Text := 'PC?';
    Comp.PartCount := 1;
    Comp.CurrentPartID := 1;
    Comp.DisplayMode := 0;
End;

// --- attach the matching PcbLib footprint and file the component away.
Procedure EndComp(FpName : String);
Var Impl;
Begin
    Impl := Comp.AddSchImplementation;
    Impl.ModelName := FpName;
    Impl.ModelType := 'PCBLIB';
    Impl.IsCurrent := True;
    Lib.AddSchComponent(Comp);
    Lib.CurrentSchComponent := Comp;
    Comp.GraphicallyInvalidate;
End;


// Power -- 177 lands
Procedure BuildComp0;
Begin
    StartComp('ProbeCard_Power', 'Probe card lands -- Power');
    AddRect(0, 0, 1200, 17800);
    AddPin(0, -100, 'T25', 'VDD08');
    AddPin(0, -200, 'T28', 'VDD08');
    AddPin(0, -300, 'T63', 'VDD08');
    AddPin(0, -400, 'B24', 'VDD08');
    AddPin(0, -500, 'B27', 'VDD08');
    AddPin(0, -600, 'L31', 'VDD08');
    AddPin(0, -700, 'R34', 'VDD08');
    AddPin(0, -800, 'B42', 'VDD08BIAS<0>');
    AddPin(0, -900, 'B43', 'VDD08BIAS<0>');
    AddPin(0, -1000, 'B8', 'VDD08BIAS<1>');
    AddPin(0, -1100, 'B9', 'VDD08BIAS<1>');
    AddPin(0, -1200, 'T2', 'VDD08D');
    AddPin(0, -1300, 'T9', 'VDD08D');
    AddPin(0, -1400, 'T26', 'VDD08D');
    AddPin(0, -1500, 'T35', 'VDD08D');
    AddPin(0, -1600, 'T44', 'VDD08D');
    AddPin(0, -1700, 'T53', 'VDD08D');
    AddPin(0, -1800, 'T62', 'VDD08D');
    AddPin(0, -1900, 'T75', 'VDD08D');
    AddPin(0, -2000, 'B25', 'VDD08D');
    AddPin(0, -2100, 'L11', 'VDD08D');
    AddPin(0, -2200, 'L18', 'VDD08D');
    AddPin(0, -2300, 'L19', 'VDD08D');
    AddPin(0, -2400, 'L23', 'VDD08D');
    AddPin(0, -2500, 'L24', 'VDD08D');
    AddPin(0, -2600, 'L25', 'VDD08D');
    AddPin(0, -2700, 'R31', 'VDD08D');
    AddPin(0, -2800, 'T37', 'VDD08DLL<0>');
    AddPin(0, -2900, 'T42', 'VDD08DLL<1>');
    AddPin(0, -3000, 'B36', 'VDD08DLL<2>');
    AddPin(0, -3100, 'B41', 'VDD08DLL<3>');
    AddPin(0, -3200, 'B15', 'VDD08DLL<4>');
    AddPin(0, -3300, 'B10', 'VDD08DLL<5>');
    AddPin(0, -3400, 'T13', 'VDD08DLL<6>');
    AddPin(0, -3500, 'T11', 'VDD08DLL<7>');
    AddPin(0, -3600, 'R9', 'VDD08LED');
    AddPin(0, -3700, 'R15', 'VDD08LED');
    AddPin(0, -3800, 'R18', 'VDD08LED');
    AddPin(0, -3900, 'R24', 'VDD08LED');
    AddPin(0, -4000, 'T8', 'VDD08PA');
    AddPin(0, -4100, 'T17', 'VDD08PA');
    AddPin(0, -4200, 'T20', 'VDD08PA');
    AddPin(0, -4300, 'T27', 'VDD08PA');
    AddPin(0, -4400, 'T33', 'VDD08PA');
    AddPin(0, -4500, 'T36', 'VDD08PA');
    AddPin(0, -4600, 'B16', 'VDD08PA');
    AddPin(0, -4700, 'B19', 'VDD08PA');
    AddPin(0, -4800, 'B26', 'VDD08PA');
    AddPin(0, -4900, 'B32', 'VDD08PA');
    AddPin(0, -5000, 'B35', 'VDD08PA');
    AddPin(0, -5100, 'L32', 'VDD08PA');
    AddPin(0, -5200, 'L33', 'VDD08PA');
    AddPin(0, -5300, 'L34', 'VDD08PA');
    AddPin(0, -5400, 'T23', 'VDD08TIA');
    AddPin(0, -5500, 'T30', 'VDD08TIA');
    AddPin(0, -5600, 'B22', 'VDD08TIA');
    AddPin(0, -5700, 'B29', 'VDD08TIA');
    AddPin(0, -5800, 'T45', 'VDD12LED');
    AddPin(0, -5900, 'T51', 'VDD12LED');
    AddPin(0, -6000, 'T57', 'VDD12LED');
    AddPin(0, -6100, 'B44', 'VDD12LED');
    AddPin(0, -6200, 'B50', 'VDD12LED');
    AddPin(0, -6300, 'B51', 'VDD12LED');
    AddPin(0, -6400, 'B56', 'VDD12LED');
    AddPin(0, -6500, 'B57', 'VDD12LED');
    AddPin(0, -6600, 'R10', 'VDD12LED');
    AddPin(0, -6700, 'R16', 'VDD12LED');
    AddPin(0, -6800, 'R19', 'VDD12LED');
    AddPin(0, -6900, 'R25', 'VDD12LED');
    AddPin(0, -7000, 'L30', 'VDD18A');
    AddPin(0, -7100, 'L21', 'VDD18B');
    AddPin(0, -7200, 'R39', 'VDD18C');
    AddPin(0, -7300, 'B6', 'VDD18D');
    AddPin(0, -7400, 'T64', 'VDD18E');
    AddPin(0, -7500, 'B52', 'VDD18LED');
    AddPin(0, -7600, 'R5', 'VDD18LED');
    AddPin(0, -7700, 'R29', 'VDD18LED');
    AddPin(0, -7800, 'T38', 'VDD18PLL<0>');
    AddPin(0, -7900, 'T41', 'VDD18PLL<1>');
    AddPin(0, -8000, 'B37', 'VDD18PLL<2>');
    AddPin(0, -8100, 'B40', 'VDD18PLL<3>');
    AddPin(0, -8200, 'B14', 'VDD18PLL<4>');
    AddPin(0, -8300, 'B11', 'VDD18PLL<5>');
    AddPin(0, -8400, 'T15', 'VDD18PLL<6>');
    AddPin(0, -8500, 'T12', 'VDD18PLL<7>');
    AddPin(0, -8600, 'B33', 'VDD18_BG<0>');
    AddPin(0, -8700, 'B18', 'VDD18_BG<1>');
    AddPin(0, -8800, 'T48', 'VDD50LED');
    AddPin(0, -8900, 'T54', 'VDD50LED');
    AddPin(0, -9000, 'T60', 'VDD50LED');
    AddPin(0, -9100, 'B47', 'VDD50LED');
    AddPin(0, -9200, 'B53', 'VDD50LED');
    AddPin(0, -9300, 'B59', 'VDD50LED');
    AddPin(0, -9400, 'B60', 'VDD50LED');
    AddPin(0, -9500, 'B61', 'VDD50LED');
    AddPin(0, -9600, 'R6', 'VDD50LED');
    AddPin(0, -9700, 'R7', 'VDD50LED');
    AddPin(0, -9800, 'R13', 'VDD50LED');
    AddPin(0, -9900, 'R22', 'VDD50LED');
    AddPin(0, -10000, 'R28', 'VDD50LED');
    AddPin(0, -10100, 'T19', 'VDD50PD');
    AddPin(0, -10200, 'L39', 'VDDPST');
    AddPin(0, -10300, 'R45', 'VDDPST');
    AddPin(0, -10400, 'T1', 'VSS');
    AddPin(0, -10500, 'T3', 'VSS');
    AddPin(0, -10600, 'T5', 'VSS');
    AddPin(0, -10700, 'T6', 'VSS');
    AddPin(0, -10800, 'T14', 'VSS');
    AddPin(0, -10900, 'T18', 'VSS');
    AddPin(0, -11000, 'T21', 'VSS');
    AddPin(0, -11100, 'T32', 'VSS');
    AddPin(0, -11200, 'T39', 'VSS');
    AddPin(0, -11300, 'T71', 'VSS');
    AddPin(0, -11400, 'T72', 'VSS');
    AddPin(0, -11500, 'T74', 'VSS');
    AddPin(0, -11600, 'T76', 'VSS');
    AddPin(0, -11700, 'B1', 'VSS');
    AddPin(0, -11800, 'B3', 'VSS');
    AddPin(0, -11900, 'B12', 'VSS');
    AddPin(0, -12000, 'B13', 'VSS');
    AddPin(0, -12100, 'B17', 'VSS');
    AddPin(0, -12200, 'B20', 'VSS');
    AddPin(0, -12300, 'B31', 'VSS');
    AddPin(0, -12400, 'B34', 'VSS');
    AddPin(0, -12500, 'B38', 'VSS');
    AddPin(0, -12600, 'L1', 'VSS');
    AddPin(0, -12700, 'L6', 'VSS');
    AddPin(0, -12800, 'L8', 'VSS');
    AddPin(0, -12900, 'L9', 'VSS');
    AddPin(0, -13000, 'L10', 'VSS');
    AddPin(0, -13100, 'L12', 'VSS');
    AddPin(0, -13200, 'L13', 'VSS');
    AddPin(0, -13300, 'L14', 'VSS');
    AddPin(0, -13400, 'L17', 'VSS');
    AddPin(0, -13500, 'L26', 'VSS');
    AddPin(0, -13600, 'L27', 'VSS');
    AddPin(0, -13700, 'L38', 'VSS');
    AddPin(0, -13800, 'L40', 'VSS');
    AddPin(0, -13900, 'R32', 'VSS');
    AddPin(0, -14000, 'R38', 'VSS');
    AddPin(0, -14100, 'R41', 'VSS');
    AddPin(0, -14200, 'R43', 'VSS');
    AddPin(0, -14300, 'R44', 'VSS');
    AddPin(0, -14400, 'R46', 'VSS');
    AddPin(0, -14500, 'T47', 'VSSLED');
    AddPin(0, -14600, 'T50', 'VSSLED');
    AddPin(0, -14700, 'T56', 'VSSLED');
    AddPin(0, -14800, 'T59', 'VSSLED');
    AddPin(0, -14900, 'B46', 'VSSLED');
    AddPin(0, -15000, 'B48', 'VSSLED');
    AddPin(0, -15100, 'B49', 'VSSLED');
    AddPin(0, -15200, 'B54', 'VSSLED');
    AddPin(0, -15300, 'B55', 'VSSLED');
    AddPin(0, -15400, 'B58', 'VSSLED');
    AddPin(0, -15500, 'B62', 'VSSLED');
    AddPin(0, -15600, 'B63', 'VSSLED');
    AddPin(0, -15700, 'B64', 'VSSLED');
    AddPin(0, -15800, 'B65', 'VSSLED');
    AddPin(0, -15900, 'B66', 'VSSLED');
    AddPin(0, -16000, 'R1', 'VSSLED');
    AddPin(0, -16100, 'R2', 'VSSLED');
    AddPin(0, -16200, 'R3', 'VSSLED');
    AddPin(0, -16300, 'R4', 'VSSLED');
    AddPin(0, -16400, 'R8', 'VSSLED');
    AddPin(0, -16500, 'R11', 'VSSLED');
    AddPin(0, -16600, 'R12', 'VSSLED');
    AddPin(0, -16700, 'R14', 'VSSLED');
    AddPin(0, -16800, 'R17', 'VSSLED');
    AddPin(0, -16900, 'R20', 'VSSLED');
    AddPin(0, -17000, 'R23', 'VSSLED');
    AddPin(0, -17100, 'R26', 'VSSLED');
    AddPin(0, -17200, 'L36', 'VSSPST');
    AddPin(0, -17300, 'R42', 'VSSPST');
    AddPin(0, -17400, 'T24', 'VSSTIA');
    AddPin(0, -17500, 'T29', 'VSSTIA');
    AddPin(0, -17600, 'B23', 'VSSTIA');
    AddPin(0, -17700, 'B28', 'VSSTIA');
    EndComp('ProbeCard_Power');
End;

// Digital -- 22 lands
Procedure BuildComp1;
Begin
    StartComp('ProbeCard_Digital', 'Probe card lands -- Digital');
    AddRect(0, 0, 1200, 2300);
    AddPin(0, -100, 'L7', 'CHIP_ID<0>');
    AddPin(0, -200, 'L5', 'CHIP_ID<1>');
    AddPin(0, -300, 'L3', 'CHIP_ID<2>');
    AddPin(0, -400, 'T34', 'CSB');
    AddPin(0, -500, 'T58', 'DFT_SCAN_SDI<1>');
    AddPin(0, -600, 'T61', 'DFT_SCAN_SDI<2>');
    AddPin(0, -700, 'T73', 'DFT_SCN_SDO<1>');
    AddPin(0, -800, 'T70', 'DFT_SCN_SDO<2>');
    AddPin(0, -900, 'T67', 'F');
    AddPin(0, -1000, 'T16', 'LB_PCLK');
    AddPin(0, -1100, 'T22', 'RESET_N');
    AddPin(0, -1200, 'T55', 'SCAN_CLK');
    AddPin(0, -1300, 'T52', 'SCAN_EN');
    AddPin(0, -1400, 'T40', 'SCAN_MODE');
    AddPin(0, -1500, 'T46', 'SCAN_SAFE_MODE');
    AddPin(0, -1600, 'T43', 'SCK');
    AddPin(0, -1700, 'T10', 'SCL');
    AddPin(0, -1800, 'T7', 'SDA');
    AddPin(0, -1900, 'T31', 'SDI');
    AddPin(0, -2000, 'T4', 'SEL_APB_SPI_N');
    AddPin(0, -2100, 'L4', 'V3_CHIP ID<0>');
    AddPin(0, -2200, 'L2', 'V3_CHIP ID<1>');
    EndComp('ProbeCard_Digital');
End;

// Analog -- 19 lands
Procedure BuildComp2;
Begin
    StartComp('ProbeCard_Analog', 'Probe card lands -- Analog');
    AddRect(0, 0, 1200, 2000);
    AddPin(0, -100, 'R40', 'LED_I0_CURRENT');
    AddPin(0, -200, 'R33', 'LED_I0_SNS');
    AddPin(0, -300, 'R36', 'LED_I1_SNS');
    AddPin(0, -400, 'T65', 'REXT1');
    AddPin(0, -500, 'T68', 'REXT2');
    AddPin(0, -600, 'B5', 'RSSI_L');
    AddPin(0, -700, 'B7', 'RSSI_R');
    AddPin(0, -800, 'L28', 'VATB_DLL');
    AddPin(0, -900, 'T69', 'VATB_LED0');
    AddPin(0, -1000, 'T66', 'VATB_LED1');
    AddPin(0, -1100, 'L22', 'VATB_RSSI0');
    AddPin(0, -1200, 'L20', 'VATB_RSSI1');
    AddPin(0, -1300, 'L29', 'VATB_TIA');
    AddPin(0, -1400, 'R27', 'VDD08D_SNS');
    AddPin(0, -1500, 'B21', 'VDD08PA_SNS');
    AddPin(0, -1600, 'B30', 'VDD08TIA_SNS');
    AddPin(0, -1700, 'T49', 'VDD50LED_SNS');
    AddPin(0, -1800, 'R21', 'VDDDRVLED_SNS');
    AddPin(0, -1900, 'R30', 'VDDLED_SNS');
    EndComp('ProbeCard_Analog');
End;

// RF-DIFFERENTIAL PAIR 100 OHM -- 6 lands
Procedure BuildComp3;
Begin
    StartComp('ProbeCard_RF_DIFFERENTIAL_PAIR_100_OHM', 'Probe card lands -- RF-DIFFERENTIAL PAIR 100 OHM');
    AddRect(0, 0, 1200, 700);
    AddPin(0, -100, 'B45', 'CLKEXTP<0>');
    AddPin(0, -200, 'B39', 'CLKEXTM<0>');
    AddPin(0, -300, 'L35', 'CLKEXTP<1>');
    AddPin(0, -400, 'L37', 'CLKEXTM<1>');
    AddPin(0, -500, 'B2', 'CLKOUTP_MUX');
    AddPin(0, -600, 'B4', 'CLKOUTN_MUX');
    EndComp('ProbeCard_RF_DIFFERENTIAL_PAIR_100_OHM');
End;

// RF-SINGLE ENDED 50 OHM -- 4 lands
Procedure BuildComp4;
Begin
    StartComp('ProbeCard_RF_SINGLE_ENDED_50_OHM', 'Probe card lands -- RF-SINGLE ENDED 50 OHM');
    AddRect(0, 0, 1200, 500);
    AddPin(0, -100, 'L16', 'TEST_DLL_DESKEW_CKOUT');
    AddPin(0, -200, 'R35', 'TEST_LED_STRB0_CKOUT');
    AddPin(0, -300, 'L15', 'TEST_PLL4_CKOUT');
    AddPin(0, -400, 'R37', 'TEST_TX_CKOUT');
    EndComp('ProbeCard_RF_SINGLE_ENDED_50_OHM');
End;

Procedure GenerateSymbol;
Begin
    If SchServer = Nil Then
    Begin
        ShowMessage('SchServer is nil -- the schematic editor is not loaded.');
        Exit;
    End;
    Lib := SchServer.GetCurrentSchDocument;
    If Lib = Nil Then
    Begin
        ShowMessage('No schematic library open. Create one first: ' +
            'File > New > Library > Schematic Library, make it active, then run again.');
        Exit;
    End;
    BuildComp0;
    BuildComp1;
    BuildComp2;
    BuildComp3;
    BuildComp4;
    ShowMessage('Built 5 probe-card components ' +
        '(228 pins total). Save the .SchLib.');
End;